name: Build the LaTeX documents
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Compile
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: latexmk
      - name: Clean the build directory
        run: find build ! -name '*.pdf' -type f -exec sudo rm -f {} +
      - name: Add a prefix to each PDF
        run : find build -name '*.pdf' -type f -exec bash -c 'mv {} $(dirname {})/alexis_jeandeau_$(basename {})' \;
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Upload
        uses: actions/upload-artifact@v1.0.0
        with:
          name: alexis_jeandeau_resume_${{ steps.slug.outputs.sha7 }}
          path: build
