name: Build the LaTeX documents
on:
  pull_request:
    branches:
      - master
    paths:
      - "**.tex"
      - "**.jpg"
      - .latexmkrc
      - .github/workflows/build.yml
  push:
    branches:
      - master
    paths:
      - "**.tex"
      - "**.jpg"
      - .latexmkrc
      - .github/workflows/build.yml
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Compile
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: make
      - name: Clean the build directory
        run: find build ! -name '*.pdf' -type f -exec sudo rm -f {} +
      - name: Linearize (optimize) each PDF
        run : find build -name '*.pdf' -type f -exec qpdf --linearize --newline-before-endstream --replace-input {} \;
      - name: Add a prefix to each PDF
        run : find build -name '*.pdf' -type f -exec bash -c 'sudo mv {} $(dirname {})/alexis_jeandeau_$(basename {})' \;
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: alexis_jeandeau_resume_${{ steps.slug.outputs.sha7 }}
          path: build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
          clean: true
          single-commit: true
